### PR TITLE
Fix netint mac compile errors

### PR DESCRIPTION
**Pull request by elv-reza**
- This patch fixes the netint ffmpeg compile errors on mac by avoiding compilation of netint related files on mac.
- Netint related files will be compile only on non-mac environments.

### CODE REVIEW

**Comment by elv-john** [comment]
Is there any Eluvio code intermingled in these NetInt sections/files?  Would it not be easier to back out the NetInt patches and apply the patch only on the relevant platform?  This way, we can update the newer FFMpeg and NetInt libxcoder in the future?

**Comment by elv-reza** [comment]
> Is there any Eluvio code intermingled in these NetInt sections/files? Would it not be easier to back out the NetInt patches and apply the patch only on the relevant platform? This way, we can update the newer FFMpeg and NetInt libxcoder in the future?

The files that are changed are netint files and don't impact ffmpeg. These files are part of netint integration with ffmpeg that are coming with netint patches. 
In addition, upgrading ffmpeg is going to be a hassle anyway due to changes that we have in ffmpeg, so nothing would become easier or harder in this area.

**Comment by elv-john** [comment]
> > Is there any Eluvio code intermingled in these NetInt sections/files? Would it not be easier to back out the NetInt patches and apply the patch only on the relevant platform? This way, we can update the newer FFMpeg and NetInt libxcoder in the future?
> 
> The files that are changed are netint files and don't impact ffmpeg. These files are part of netint integration with ffmpeg that are coming with netint patches. In addition, upgrading ffmpeg is going to be a hassle anyway due to changes that we have in ffmpeg, so nothing would become easier or harder in this area.

Wouldn't it be easier to just have to deal with our code only, especially if NetInt has massive changes in subsequent FFMpeg versions?

**Comment by elv-reza** [comment]
> > > Is there any Eluvio code intermingled in these NetInt sections/files? Would it not be easier to back out the NetInt patches and apply the patch only on the relevant platform? This way, we can update the newer FFMpeg and NetInt libxcoder in the future?
> > 
> > 
> > The files that are changed are netint files and don't impact ffmpeg. These files are part of netint integration with ffmpeg that are coming with netint patches. In addition, upgrading ffmpeg is going to be a hassle anyway due to changes that we have in ffmpeg, so nothing would become easier or harder in this area.
> 
> Wouldn't it be easier to just have to deal with our code only, especially if NetInt has massive changes in subsequent FFMpeg versions?

These are the changes that had to be done by netint in the first place. Actually, I will send them a message and will propose them to do these changes in their patch. Hopefully, we will not see these kind of things in future...

**Pull request merged**
